- .circleci/config.yml
- feat-content-example.html
testing circle build and s3 deploy on PR merge
> test circle build on PR merge

- feat-content-example.html
test if PR will override existing s3 file and if local build will automatically update feat-content
> check if update syncs with local ui build

- .circleci/config.yml
- feat-content-example.html
styling fix and testing PR merge from develop to master
> styling fix, test develop

- feat-content.html
Preliminary featured content, plus testing if AWS bucket changes work. Also changed links to open in new tab.
> Draft 1.8 featured content

- feat-content.html
> add BCC2020, remove GATK collection

- feat-content.html
merge BCC2020 feat content changes to prod/master
> remove GATK collection, add BCC2020 for production

- feat-content.html
> Add bdc fellows covid-19 workflow collection

- feat-content.html
> Update about GitHub Apps filters

- feat-content.html
https://ucsc-cgl.atlassian.net/browse/SEAB-1743
> highlight Beth's video

- feat-content.html
might as well get this ready for 1.11 / hotfix
> sync master with develop

- .circleci/config.yml
Don't mix names of servers with branch names
> Consistent branches 

- .circleci/config.yml
Master version of https://github.com/dockstore/extra-content/pull/26
> Consistent paths

- .circleci/config.yml
- news.html
Merging to master, which will make it appear in prod.
> COVID featured collections

- news.html
I'm reviewing this ticket: https://ucsc-cgl.atlassian.net/browse/SEAB-3063, so I'm editing the news slightly to verify that the cloudfront invalidation works
> Edit news to verify cloudfront invalidation

- .circleci/config.yml
https://ucsc-cgl.atlassian.net/browse/SEAB-2852
> Use CircleCI context, which requires workflow

- .circleci/config.yml
Email noted
https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic
> circle-ci recommendation

- news.html
There were lots of trailing spaces that I got rid of as well.
> Update news for 1.12 release

- news.html
fix link 
(see friendly CI maven replacing maven release + hubflow presentation)
> change link from hf release to maven release

- .circleci/config.yml
more https://ucsc-cgl.atlassian.net/browse/SEAB-4284
on merge, will deactivate keys in old context
> switch to openid connect

- news.html
- Recent blog posts (security, 1.12, AWS)
- Recent webinar (eLwazi)
> News updates from March to July

- feat-content.html
- Added HPRC org with linked tutorials
- New WARP collection
- Added FAIR workflows video
> Updating featured content

- feat-content.html
Four looked off in dev display, so I removed the older intro video to have 3 panels only in featured content.
> 3 panels in featured content

- news.html
This is a hotfix, ultimately going to master (the merge to develop will be gnarly, sigh). So it doesn't have Kim's changes for styling nor attempt to address block inside inline elements issue.
https://ucsc-cgl.atlassian.net/browse/SEAB-5314
Screenshot of unstyled HTML:
> Update news with 1.13 and CLI validator

- news.html
Since metrics and notebooks are in preview, just going to keep it simple, unless anybody else has any ideas.
> Add 1.14 news

- .circleci/config.yml
Added build-time check for valid html as per [SEAB-663](https://ucsc-cgl.atlassian.net/browse/SEAB-663).
[SEAB-663]: https://ucsc-cgl.atlassian.net/browse/SEAB-663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SEAB-663: Check for valid html during build

- news.html
> Update for 1.15 release

- news.html
> Add Terra metrics load - 2H 2024
